# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
