# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0002_auto_20170915_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
