# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0004_organisation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date added'),
            preserve_default=False,
        ),
    ]
