# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0005_labels_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='site',
            new_name='sites',
        ),
    ]
