# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0007_auto_20171008_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='labels',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['id']},
        ),
    ]
