# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0008_auto_20171009_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
