# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0009_auto_20171016_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
