# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0010_auto_20171017_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
