# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0011_auto_20171017_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
