# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0017_auto_20171101_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=True, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='labels',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=False),
        ),
    ]
