# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:02
from __future__ import unicode_literals

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    for m in ['Job', 'Organisation', 'Labels', 'Site']:
        M = apps.get_model('vol', m)
        for row in M.objects.all():
            row.uuid = uuid.uuid4()
            row.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('vol', '0018_auto_20171101_2358'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
