# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0017_auto_20171105_2306'),
        ('vol', '0020_auto_20171102_0003'),
    ]

    operations = [
    ]
