# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0024_auto_20171106_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.CharField(max_length=2083, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=2083, unique=True),
        ),
    ]
