# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 20:15
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations

from vol.models import Labels, Organisation, Site, Job


def migrate_data_forward(apps, schema_editor):
    for instance in Labels.objects.all():
        print("Generating slug for %s" % instance)
        instance.save()  # Will trigger slug update

    for instance in Organisation.objects.all():
        print("Generating slug for %s" % instance)
        instance.save()  # Will trigger slug update

    for instance in Site.objects.all():
        print("Generating slug for %s" % instance)
        instance.save()  # Will trigger slug update

    for instance in Job.objects.all():
        print("Generating slug for %s" % instance)
        instance.save()  # Will trigger slug update


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('vol', '0025_auto_20171106_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True, null=True, default=None, editable=False,
                                                populate_from='title'),
        ),
        migrations.AddField(
            model_name='labels',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True, null=True, default=None, editable=False,
                                                populate_from='name'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True, null=True, default=None, editable=False,
                                                populate_from='name'),
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True, null=True, default=None, editable=False,
                                                populate_from='name'),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
