# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0027_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_jobs',
            field=models.ManyToManyField(blank=True, to='vol.Job'),
        ),
    ]
