from django.conf.urls import url, include
from django.views.generic.base import RedirectView

from rest_framework import routers
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer

from . import views

schema_view = get_schema_view(title="Vol.community API",
                                  renderer_classes=[OpenAPIRenderer, SwaggerUIRenderer]
                              )

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'labels', views.LabelViewSet)
router.register(r'organisations', views.OrganisationViewSet)
router.register(r'sites', views.SiteViewSet)
router.register(r'jobs', views.JobViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    # Allow clients to explore our API using Swagger
    url(r'swagger', schema_view),

    # Redirects to /api to make urls generated by django-rest-api and the swagger
    # plug work as advertised -without the trailing slash urls would look like:
    # "http://127.0.0.1:8000/apijobs" instead of "http://127.0.0.1:8000/api/jobs"
    url(r'^$', RedirectView.as_view(url='/api/', permanent=False), name='index'),

    url(r'/', include(router.urls)),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]
